[package]
name = "rinha-samuelpanzera-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
may_minihttp = "0.1.11"
may = { version = "0.3.51", default-features = false }
tokio = { version = "1.40", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }


serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
hostname = "0.4.1"
chrono = { version = "0.4.38", features = ["serde"] }

uuid = { version = "1.17", features = ["v4", "serde"] }
rust_decimal = { version = "1.37.2", features = ["serde"] }
memmap2 = "0.9"

[profile.release]
opt-level = 3